version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - cache

  mysql:
    container_name: mysql
    image: mysql:8.0
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: db
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: password
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  cache:
    container_name: cache
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
